### PR TITLE
Added RestrictEvents info to Extensions section

### PR DESCRIPTION
**Pull request by Pavo-IM**

### CODE REVIEW

**Comment by Lorys89** [comment]
add https://github.com/Mieze/LucyRTL8125Ethernet and https://github.com/CloverHackyColor/FakeSMC3_with_plugins

**Comment by Lorys89** [comment]
thx ❤️

**Comment by Lorys89** [comment]
IMG_20210518_221029_825
and you can fix under series so that recognizes it as 400 series

**Comment by headkaze** [comment]
Thanks Pavo! Is it possible to put back NullCPUPowerManagement and Shiki? The reason I leave them in there is so people who're using old and outdated kexts can see that they are "Replaced By" something else; otherwise they 're not detected at all.

**Comment by Pavo-IM** [comment]
> IMG_20210518_221029_825
> and you can fix under series so that recognizes it as 400 series

I don't think there is any good way of doing this, because the USB Controllers are used on a lot of different chipset types.

**Pull request merged**
