### PR TITLE
Update fallback method to support checking FW status in macOS Monterey

### PR DESCRIPTION
**Pull request by williambj1**
Hi @headkaze!

This PR introduces a simple fix to support checking FW status in macOS Monterey.
It does not fix the issue where unknown Bluetooth devices (ones that are not included in the plist files) not being detected.

**Background Info:**
In macOS Monterey Apple deprecated `IOBluetoothHostControllerTransport` and introduced a new framework that runs in userspace. Here is a screenshot for reference.

image

### CODE REVIEW

**Comment by headkaze** [comment]
Is there a reason why you closed this?

**Comment by headkaze** [comment]
Can you please check out 3.6.4 and let me know if it detects your BT device in Monterey.

**Comment by williambj1** [comment]
It works! Thanks!

**Comment by headkaze** [comment]
Great! Thanks for your contributions!

**Pull request closed without merging**
