### PR TITLE
Add zh-Hans.lproj

### PR DESCRIPTION
**Pull request by williambj1**
Co-Authored-By: daliansky <daliansky2008@gmail.com>
Co-Authored-By: Startpenghubingzhou <lengku384120429@icloud.com>

### CODE REVIEW

**Comment by williambj1** [comment]
Hi! @headkaze 
Updated for v2.3.9
Please have a look!

Bat.bat

**Comment by headkaze** [comment]
I apologize I forgot to commit the Localizable.strings. Please add your
changes to the new commit.

**Comment by williambj1** [comment]
Fixed :)

**Comment by williambj1** [comment]
So the Korean version is ok to be based on?

**Comment by headkaze** [comment]
The Chinese version has also been updated to match. Just update the English
that hasn't been translated. If I've missed anything let me know and then
I'll commit an update for all languages to include it.

So this is how I'm going to do this going forward. I will
update Localizable.strings with English entries and then everyone can
translate at their pleasure.

**Comment by williambj1** [comment]
Thanks, I'm already working on rewriting the localization.strings, please wait until I finish.

**Comment by williambj1** [comment]
@headkaze 
I discovered that lots of punctuations such as ":" are changed, is it a mistake or there will be a big update for the interface?

**Comment by williambj1** [comment]
Missing:
Use Intel HDMI

**Comment by williambj1** [comment]
Missing 2:
"Missing or incompatible nasm!" = "丢失或者不匹配版本的nasm！";
"Click OK to run installation." = "点按确定来运行安装。";
"Add Resolution" = "添加缩放";
"Delete Resolution" = "删除缩放";

**Pull request closed without merging**
